version: '3.8'

services:
  email-service:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MAX_RETRIES=3
      - BASE_DELAY_MS=1000
      - RATE_LIMIT_PER_MINUTE=50
      - CIRCUIT_BREAKER_THRESHOLD=3
      - CIRCUIT_BREAKER_TIMEOUT=30000
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Optional: Add nginx for production load balancing/reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - email-service
    restart: unless-stopped
    profiles:
      - production
